### ISSUE TITLE
unable start npm-proxy-cache on windows

### ISSUE THREAD

**Issue by babunallamothu** [runk/npm-proxy-cache#13]
Tried to set up npm-proxy-cache in my local windows machine facing some problem while making server start, could some one help me out. Thanks!

C:\Users\user>npm-proxy-cache

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1020:19)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1121:5)
    at Object.exports.powerup (C:\Users\user\AppData\Roaming\npm\node_modules\npm-proxy-cache\lib\proxy.js:44:45)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\npm-proxy-cache\bin\npm-proxy-cache:19:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by AMoghrabi** [comment]
was this ever resolved? I'm having the same issue. Even running flag commands such as -v produces this error.

**Comment by someuser77** [comment]
I'm having the same issue on Windows 7 x64. Node running as 32 bit process.
