### ISSUE TITLE
Request path contains unescaped characters

### ISSUE THREAD

**Issue by Siggen** [runk/npm-proxy-cache#15]
I'm getting the following crash when calling resources with dash ('-') in url:

	[2015-09-16 09:36:46.351] [WARN] proxy - direct http://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
	_http_client.js:73
	    throw new TypeError('Request path contains unescaped characters.');
		  ^
	TypeError: Request path contains unescaped characters.
	    at new ClientRequest (_http_client.js:73:11)
	    at TunnelingAgent.exports.request (http.js:49:10)
	    at TunnelingAgent.createSocket (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/node_modules/tunnel-agent/index.js:117:25)
	    at TunnelingAgent.createSecureSocket [as createSocket] (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/node_modules/tunnel-agent/index.js:184:41)
	    at TunnelingAgent.addRequest (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/node_modules/tunnel-agent/index.js:80:8)
	    at new ClientRequest (_http_client.js:154:16)
	    at Object.exports.request (http.js:49:10)
	    at Object.exports.request (https.js:136:15)
	    at Request.start (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/request.js:584:30)
	    at Request.end (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/request.js:1212:28)
	error: Forever detected script exited with code: 1
	error: Script restart attempt #37

Is there some urlEncoding missing ?

**Comment by Siggen** [comment]
Sorry, I forgot to tell I'm using npm-proxy-cache version 0.2.1. I'll try with the version 0.2.3...

**Comment by runk** [comment]
Cannot reproduce it :( Can you provide more details?

What I tried:

```
npm-proxy-cache -p 10000
curl -x http://localhost:10000 http://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
```

No errors.

**Comment by Siggen** [comment]
Hi runk,

Thanks for you comment. I installed version 0.2.3 and I'm still seeing the problem:

	    [2015-09-17 03:34:30.310] [WARN] proxy - direct http://github.com/angular/bower-angular/archive/v1.3.19.tar.gz
	    _http_client.js:73
		throw new TypeError('Request path contains unescaped characters.');
		      ^
	    TypeError: Request path contains unescaped characters.
		at new ClientRequest (_http_client.js:73:11)
		at TunnelingAgent.exports.request (http.js:49:10)
		at TunnelingAgent.createSocket (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/node_modules/tunnel-agent/index.js:117:25)
		at TunnelingAgent.createSecureSocket [as createSocket] (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/node_modules/tunnel-agent/index.js:184:41)
		at TunnelingAgent.addRequest (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/node_modules/tunnel-agent/index.js:80:8)
		at new ClientRequest (_http_client.js:154:16)
		at Object.exports.request (http.js:49:10)
		at Object.exports.request (https.js:136:15)
		at Request.start (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/request.js:584:30)
		at Request.end (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/request.js:1212:28)
	    error: Forever detected script exited with code: 1
	    error: Script restart attempt #1

... but obviously the URL in the log has no unescaped character. 

I'll add some logging to print the URL and I'll come back to you.

Thank you !

**Comment by runk** [comment]
Can you try that simple isolated test I posted in previous comment?

**Comment by Siggen** [comment]
Yes, here is the result (+ extra logging I added): 

	[2015-09-17 11:54:57.211] [WARN] proxy - direct http://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
	make request http://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
	make request http://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
	make request https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
	_http_client.js:73
	    throw new TypeError('Request path contains unescaped characters.');
		  ^
	TypeError: Request path contains unescaped characters.
	    at new ClientRequest (_http_client.js:73:11)
	    at TunnelingAgent.exports.request (http.js:49:10)
	    at TunnelingAgent.createSocket (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/node_modules/tunnel-agent/index.js:117:25)
	    at TunnelingAgent.createSecureSocket [as createSocket] (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/node_modules/tunnel-agent/index.js:184:41)
	    at TunnelingAgent.addRequest (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/node_modules/tunnel-agent/index.js:80:8)
	    at new ClientRequest (_http_client.js:154:16)
	    at Object.exports.request (http.js:49:10)
	    at Object.exports.request (https.js:136:15)
	    at Request.start (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/request.js:585:30)
	    at Request.end (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/request.js:1213:28)
	error: Forever detected script exited with code: 1
	error: Script restart attempt #1

Now, I'm starting the think I've got a problem with my setup...

**Comment by Siggen** [comment]
Ok, I upgraded nodejs to version 4.1.0 and reinstalled npm-proxy-cache:

    $ npm install npm-proxy-cache
    npm-proxy-cache@0.2.3 node_modules/npm-proxy-cache
    ├── commander@2.0.0
    ├── mkdirp@0.3.5
    ├── request@2.27.0 (forever-agent@0.5.2, tunnel-agent@0.3.0, aws-sign@0.3.0, qs@0.6.6, oauth-sign@0.3.0, mime@1.2.11, cookie-jar@0.3.0, json-stringify-safe@5.0.1, node-uuid@1.4.3, http-signature@0.10.1, form-data@0.1.4, hawk@1.0.0)
    └── log4js@0.6.8 (dequeue@1.0.3, semver@1.1.4, async@0.1.15, readable-stream@1.0.33)

Then I started npm-proxy-cache with this command:

    $ node_modules/npm-proxy-cache/bin/npm-proxy-cache --host 10.120.134.47 --port 3333 --ttl $TTL --expired --storage ~/npm-proxy-cache/data --proxy $PROXY

Then I ran:

    $ curl -x http://<server>:3333 http://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
    curl: (52) Empty reply from server

Log says:

    [2015-09-17 12:42:53.064] [INFO] proxy - Listening on 10.120.134.47:3333 [28899]
    [2015-09-17 12:42:56.463] [WARN] proxy - direct http://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
    _http_client.js:51
	throw new TypeError('Request path contains unescaped characters.');
	^

    TypeError: Request path contains unescaped characters.
	at new ClientRequest (_http_client.js:51:11)
	at TunnelingAgent.exports.request (http.js:31:10)
	at TunnelingAgent.createSocket (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/node_modules/tunnel-agent/index.js:117:25)
	at TunnelingAgent.createSecureSocket [as createSocket] (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/node_modules/tunnel-agent/index.js:184:41)
	at TunnelingAgent.addRequest (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/node_modules/tunnel-agent/index.js:80:8)
	at new ClientRequest (_http_client.js:133:16)
	at Object.exports.request (http.js:31:10)
	at Object.exports.request (https.js:163:15)
	at Request.start (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/request.js:584:30)
	at Request.end (/ccv/data1/npm-proxy-cache/npm-proxy-cache/node_modules/npm-proxy-cache/node_modules/request/request.js:1212:28)

Did i miss something ?

**Comment by Siggen** [comment]
Found it ! It seems to be a bug with request@2.27.0 : https://github.com/bower/bower/issues/1674 . I manually upgraded to request@2.51.0 and npm-proxy-cache doesn't crash anymore.

**Comment by runk** [comment]
:boom: I'll upgrade `request` version to latest in `package.json`.

**Comment by Siggen** [comment]
Thanks a lot !

**Comment by runk** [comment]
`v0.3.0` published
