### ISSUE TITLE
crashes if cache directory is not on the same filesystem as /tmp

### ISSUE THREAD

**Issue by phreaker0** [runk/npm-proxy-cache#65]
i just upgraded to the latest version and this one crashes because in my setup the cache directory isn't on the same filesystem as the temporary folder, but it worked before. Relevant stacktrace:
```
Mar 26 12:21:48 proxy systemd-nspawn[32693]: [2018-03-26 10:21:48.615] [WARN] proxy - direct https://registry.npmjs.org:443/types-registry
Mar 26 12:21:48 proxy systemd-nspawn[32693]: fs.js:809
Mar 26 12:21:48 proxy systemd-nspawn[32693]:   return binding.rename(pathModule._makeLong(oldPath),
Mar 26 12:21:48 proxy systemd-nspawn[32693]:                  ^
Mar 26 12:21:48 proxy systemd-nspawn[32693]: Error: EXDEV: cross-device link not permitted, rename '/tmp/3593c226-axf103' -> '/cache/3/5/9/3593c226'
Mar 26 12:21:48 proxy systemd-nspawn[32693]:     at Error (native)
Mar 26 12:21:48 proxy systemd-nspawn[32693]:     at Object.fs.renameSync (fs.js:809:18)
Mar 26 12:21:48 proxy systemd-nspawn[32693]:     at WriteStream.<anonymous> (/usr/lib/node_modules/npm-proxy-cache/lib/cache.js:88:10)
Mar 26 12:21:48 proxy systemd-nspawn[32693]:     at emitNone (events.js:91:20)
Mar 26 12:21:48 proxy systemd-nspawn[32693]:     at WriteStream.emit (events.js:185:7)
Mar 26 12:21:48 proxy systemd-nspawn[32693]:     at finishMaybe (_stream_writable.js:514:14)
Mar 26 12:21:48 proxy systemd-nspawn[32693]:     at afterWrite (_stream_writable.js:388:3)
Mar 26 12:21:48 proxy systemd-nspawn[32693]:     at onwrite (_stream_writable.js:378:7)
Mar 26 12:21:48 proxy systemd-nspawn[32693]:     at WritableState.onwrite (_stream_writable.js:89:5)
Mar 26 12:21:48 proxy systemd-nspawn[32693]:     at fs.js:2137:5
```

**Comment by runk** [comment]
Damn. Yeah, it was introduced not a while ago. I'll work on a fix. If you'd downgrade to prev version it'd make the trick.

**Comment by runk** [comment]
v1.0.5 is out. Let me know if there're any issues with it.

Thanks for the bug report. 👍

**Comment by phreaker0** [comment]
that was fast! thx, works for me.
